apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-my-mysql
spec:
  capacity:
    storage: 9Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 # StorageClass name
  awsElasticBlockStore:
    volumeID: vol-0bad41327731e7a95
    fsType: ext4

